### ISSUE TITLE
Delete Response

### ISSUE THREAD

**Issue by Flooooooooooorian** [SimonSta95/GameHub_Capstone#22]
https://github.com/SimonSta95/GameHub_Capstone/blob/18dc2b1fcce830e8c11383ce36c061c50bd99717/gamehub-backend/src/main/java/com/example/gamehubbackend/controllers/GameController.java#L74

REST API Delete Response, status code etc

**Comment by SimonSta95** [comment]
Fixed

**Comment by SimonSta95** [comment]
Fixed
