### ISSUE TITLE
User role

### ISSUE THREAD

**Issue by Flooooooooooorian** [SimonSta95/GameHub_Capstone#24]
https://github.com/SimonSta95/GameHub_Capstone/blob/18dc2b1fcce830e8c11383ce36c061c50bd99717/gamehub-backend/src/main/java/com/example/gamehubbackend/services/UserDetailServiceImpl.java#L36

`List.of(new SimpleGrantedAuthority(user.role))`

**Comment by SimonSta95** [comment]
fixed
