### ISSUE TITLE
General method

### ISSUE THREAD

**Issue by Flooooooooooorian** [SimonSta95/GameHub_Capstone#25]
https://github.com/SimonSta95/GameHub_Capstone/blob/18dc2b1fcce830e8c11383ce36c061c50bd99717/gamehub-backend/src/main/java/com/example/gamehubbackend/services/UserService.java#L40

Methode anpassen damit sie mit userdetails und oauth funktioniert.

**Comment by SimonSta95** [comment]
@GetMapping("/me")
    public UserResponse getCurrentUser(Principal principal) {

        return userService.getLoggedInUser(principal);
    }

    public UserResponse getLoggedInUser(Principal principal) {

        if (principal instanceof OAuth2AuthenticationToken token) {
            // Handle OAuth2 authentication
            OAuth2User oAuth2User = token.getPrincipal();
            return getUserByUsername(oAuth2User.getAttributes().get("login").toString());
        }

        if (principal instanceof UsernamePasswordAuthenticationToken) {
            var userPrincipal = (org.springframework.security.core.userdetails.User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
            // Handle Username/Password authentication
            return getUserByUsername(userPrincipal.getUsername());
        }

        return null;
    }
